/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZnEmGiBpPVg
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function FlightCard({ flightInfo }: { flightInfo: any }) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center space-x-4">
          <div className="flex flex-col">
            <CardTitle>Flight AC130</CardTitle>
            <CardDescription>YUL to LGA</CardDescription>
          </div>
          <Button size="sm" variant="outline">
            $249.99
          </Button>
        </div>
      </CardHeader>
      <CardContent className="grid gap-2">
        <div className="flex items-center space-x-2">
          <PlaneTakeoffIcon className="w-4 h-4" />
          <div className="flex flex-col">
            <p className="text-sm font-medium">YUL Montreal-Trudeau</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">Montreal</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <PlaneLandingIcon className="w-4 h-4" />
          <div className="flex flex-col">
            <p className="text-sm font-medium">LGA LaGuardia</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">New York</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <PlaneIcon className="w-4 h-4" />
          <div className="flex flex-col">
            <p className="text-sm font-medium">Air Canada</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">AC130</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <ClockIcon className="w-4 h-4" />
          <div className="flex flex-col">
            <p className="text-sm font-medium">Departure</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">12:45 PM</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <ClockIcon className="w-4 h-4" />
          <div className="flex flex-col">
            <p className="text-sm font-medium">Arrival</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">3:15 PM</p>
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex justify-between">
        <Button size="sm">Save</Button>
        <Button size="sm">Edit</Button>
      </CardFooter>
    </Card>
  );
}

function PlaneTakeoffIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 22h20" />
      <path d="M6.36 17.4 4 17l-2-4 1.1-.55a2 2 0 0 1 1.8 0l.17.1a2 2 0 0 0 1.8 0L8 12 5 6l.9-.45a2 2 0 0 1 2.09.2l4.02 3a2 2 0 0 0 2.1.2l4.19-2.06a2.41 2.41 0 0 1 1.73-.17L21 7a1.4 1.4 0 0 1 .87 1.99l-.38.76c-.23.46-.6.84-1.07 1.08L7.58 17.2a2 2 0 0 1-1.22.18Z" />
    </svg>
  );
}

function PlaneLandingIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 22h20" />
      <path d="M3.77 10.77 2 9l2-4.5 1.1.55c.55.28.9.84.9 1.45s.35 1.17.9 1.45L8 8.5l3-6 1.05.53a2 2 0 0 1 1.09 1.52l.72 5.4a2 2 0 0 0 1.09 1.52l4.4 2.2c.42.22.78.55 1.01.96l.6 1.03c.49.88-.06 1.98-1.06 2.1l-1.18.15c-.47.06-.95-.02-1.37-.24L4.29 11.15a2 2 0 0 1-.52-.38Z" />
    </svg>
  );
}

function PlaneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  );
}

function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}
